arb-dir: lib/l10n
template-arb-file: app_en.arb

output-localization-file: design_system_localizations.dart
output-class: DesignSystemLocalizations

synthetic-package: false

untranslated-messages-file: lib/l10n/untranslated_messages.json