name: design_system
description: "Design System Package"
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  carousel_slider: ^5.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
  fonts:
    - family: Catamaran
      fonts:
        - weight: 100
          asset: assets/fonts/Catamaran-Thin.ttf
        - weight: 200
          asset: assets/fonts/Catamaran-ExtraLight.ttf
        - weight: 300
          asset: assets/fonts/Catamaran-Light.ttf
        - weight: 400
          asset: assets/fonts/Catamaran-Regular.ttf
        - weight: 500
          asset: assets/fonts/Catamaran-Medium.ttf
        - weight: 600
          asset: assets/fonts/Catamaran-SemiBold.ttf
        - weight: 700
          asset: assets/fonts/Catamaran-Bold.ttf
        - weight: 800
          asset: assets/fonts/Catamaran-ExtraBold.ttf
        - weight: 900
          asset: assets/fonts/Catamaran-Black.ttf
    - family: Moret
      fonts:
        - asset: assets/fonts/Moret-Regular.otf
