// Mocks generated by Mockito 5.4.6 from annotations
// in healthy_living_product_detail/test/mock/mock_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:healthy_living_product_detail/src/analytics/product_details_analytics.dart'
    as _i18;
import 'package:healthy_living_product_detail/src/domain/models/cleaner_detail_request_model.dart'
    as _i8;
import 'package:healthy_living_product_detail/src/domain/models/cleaner_detail_response_model.dart'
    as _i7;
import 'package:healthy_living_product_detail/src/domain/models/cosmetic_detail_request_model.dart'
    as _i6;
import 'package:healthy_living_product_detail/src/domain/models/cosmetic_detail_response_model.dart'
    as _i5;
import 'package:healthy_living_product_detail/src/domain/models/food_detail_request_model.dart'
    as _i10;
import 'package:healthy_living_product_detail/src/domain/models/food_detail_response_model.dart'
    as _i9;
import 'package:healthy_living_product_detail/src/domain/models/ingredient_details/ingredient_info_request_model.dart'
    as _i12;
import 'package:healthy_living_product_detail/src/domain/models/ingredient_details/ingredient_info_response_model.dart'
    as _i11;
import 'package:healthy_living_product_detail/src/domain/models/product_compare_cleaners_response_model.dart'
    as _i15;
import 'package:healthy_living_product_detail/src/domain/models/product_compare_cosmetic_response_model.dart'
    as _i13;
import 'package:healthy_living_product_detail/src/domain/models/product_compare_food_response_model.dart'
    as _i16;
import 'package:healthy_living_product_detail/src/domain/models/product_compare_request_model.dart'
    as _i14;
import 'package:healthy_living_product_detail/src/domain/models/product_detail_basic_information_model.dart'
    as _i19;
import 'package:healthy_living_product_detail/src/domain/repository/product_detail_repository.dart'
    as _i3;
import 'package:healthy_living_shared/healthy_living_shared.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/network.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkResponse_0<T> extends _i1.SmartFake
    implements _i2.NetworkResponse<T> {
  _FakeNetworkResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductDetailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductDetailRepository extends _i1.Mock
    implements _i3.ProductDetailRepository {
  MockProductDetailRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse<_i5.CosmeticDetailResponseModel?>>
  getCosmeticDetails({required _i6.CosmeticDetailRequestModel? request}) =>
      (super.noSuchMethod(
            Invocation.method(#getCosmeticDetails, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i5.CosmeticDetailResponseModel?>
            >.value(
              _FakeNetworkResponse_0<_i5.CosmeticDetailResponseModel?>(
                this,
                Invocation.method(#getCosmeticDetails, [], {#request: request}),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<_i5.CosmeticDetailResponseModel?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i7.CleanerDetailResponseModel?>>
  getCleanerDetails({required _i8.CleanerDetailRequestModel? request}) =>
      (super.noSuchMethod(
            Invocation.method(#getCleanerDetails, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i7.CleanerDetailResponseModel?>
            >.value(
              _FakeNetworkResponse_0<_i7.CleanerDetailResponseModel?>(
                this,
                Invocation.method(#getCleanerDetails, [], {#request: request}),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<_i7.CleanerDetailResponseModel?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i9.FoodDetailResponseModel?>> getFoodDetails({
    required _i10.FoodDetailRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodDetails, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i9.FoodDetailResponseModel?>
            >.value(
              _FakeNetworkResponse_0<_i9.FoodDetailResponseModel?>(
                this,
                Invocation.method(#getFoodDetails, [], {#request: request}),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<_i9.FoodDetailResponseModel?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i11.IngredientInfoResponseModel?>>
  getIngredientInfo({required _i12.IngredientInfoRequestModel? request}) =>
      (super.noSuchMethod(
            Invocation.method(#getIngredientInfo, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i11.IngredientInfoResponseModel?>
            >.value(
              _FakeNetworkResponse_0<_i11.IngredientInfoResponseModel?>(
                this,
                Invocation.method(#getIngredientInfo, [], {#request: request}),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i11.IngredientInfoResponseModel?>
          >);

  @override
  _i4.Future<_i2.NetworkResponse<_i13.ProductCompareCosmeticResponseModel?>>
  cosmeticProductCompare({required _i14.ProductCompareRequestModel? request}) =>
      (super.noSuchMethod(
            Invocation.method(#cosmeticProductCompare, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i13.ProductCompareCosmeticResponseModel?>
            >.value(
              _FakeNetworkResponse_0<_i13.ProductCompareCosmeticResponseModel?>(
                this,
                Invocation.method(#cosmeticProductCompare, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i13.ProductCompareCosmeticResponseModel?>
          >);

  @override
  _i4.Future<_i2.NetworkResponse<_i15.ProductCompareCleanersResponseModel?>>
  cleanersProductCompare({required _i14.ProductCompareRequestModel? request}) =>
      (super.noSuchMethod(
            Invocation.method(#cleanersProductCompare, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i15.ProductCompareCleanersResponseModel?>
            >.value(
              _FakeNetworkResponse_0<_i15.ProductCompareCleanersResponseModel?>(
                this,
                Invocation.method(#cleanersProductCompare, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i15.ProductCompareCleanersResponseModel?>
          >);

  @override
  _i4.Future<_i2.NetworkResponse<_i16.ProductCompareFoodResponseModel?>>
  foodProductCompare({required _i14.ProductCompareRequestModel? request}) =>
      (super.noSuchMethod(
            Invocation.method(#foodProductCompare, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i16.ProductCompareFoodResponseModel?>
            >.value(
              _FakeNetworkResponse_0<_i16.ProductCompareFoodResponseModel?>(
                this,
                Invocation.method(#foodProductCompare, [], {#request: request}),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i16.ProductCompareFoodResponseModel?>
          >);
}

/// A class which mocks [HistoryProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryProductRepository extends _i1.Mock
    implements _i17.HistoryProductRepository {
  MockHistoryProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse<_i17.GeneralResponseModel?>>
  addRecentlyViewedProduct({
    required _i17.RecentlyViewedProductRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addRecentlyViewedProduct, [], {
              #request: request,
            }),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i17.GeneralResponseModel?>
            >.value(
              _FakeNetworkResponse_0<_i17.GeneralResponseModel?>(
                this,
                Invocation.method(#addRecentlyViewedProduct, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<_i17.GeneralResponseModel?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i17.GetHistoryResponseModel?>>
  getRecentlyViewed({required _i17.GetHistoryRequestModel? request}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyViewed, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i17.GetHistoryResponseModel?>
            >.value(
              _FakeNetworkResponse_0<_i17.GetHistoryResponseModel?>(
                this,
                Invocation.method(#getRecentlyViewed, [], {#request: request}),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<_i17.GetHistoryResponseModel?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i17.OcrProvisionalScoreResponseDTO?>>
  pollingOCRProvisionalScore({required String? jobId}) =>
      (super.noSuchMethod(
            Invocation.method(#pollingOCRProvisionalScore, [], {#jobId: jobId}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i17.OcrProvisionalScoreResponseDTO?>
            >.value(
              _FakeNetworkResponse_0<_i17.OcrProvisionalScoreResponseDTO?>(
                this,
                Invocation.method(#pollingOCRProvisionalScore, [], {
                  #jobId: jobId,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i17.OcrProvisionalScoreResponseDTO?>
          >);
}

/// A class which mocks [IngredientPreferenceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientPreferenceRepository extends _i1.Mock
    implements _i17.IngredientPreferenceRepository {
  MockIngredientPreferenceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
    _i2.NetworkResponse<_i17.CuratedIngredientPreferenceListsResponseModel?>
  >
  getCuratedIngredientPreferenceLists({
    required _i17.CuratedIngredientPreferenceListsRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCuratedIngredientPreferenceLists, [], {
              #request: request,
            }),
            returnValue: _i4.Future<
              _i2.NetworkResponse<
                _i17.CuratedIngredientPreferenceListsResponseModel?
              >
            >.value(
              _FakeNetworkResponse_0<
                _i17.CuratedIngredientPreferenceListsResponseModel?
              >(
                this,
                Invocation.method(#getCuratedIngredientPreferenceLists, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<
              _i17.CuratedIngredientPreferenceListsResponseModel?
            >
          >);

  @override
  _i4.Future<
    _i2.NetworkResponse<List<_i17.CuratedIngredientPreferenceListModel?>?>
  >
  getCuratedIngredientPreferences({
    required _i17.CuratedIngredientPreferenceListsRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCuratedIngredientPreferences, [], {
              #request: request,
            }),
            returnValue: _i4.Future<
              _i2.NetworkResponse<
                List<_i17.CuratedIngredientPreferenceListModel?>?
              >
            >.value(
              _FakeNetworkResponse_0<
                List<_i17.CuratedIngredientPreferenceListModel?>?
              >(
                this,
                Invocation.method(#getCuratedIngredientPreferences, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<
              List<_i17.CuratedIngredientPreferenceListModel?>?
            >
          >);

  @override
  _i4.Future<
    _i2.NetworkResponse<List<_i17.CuratedIngredientPreferenceListModel?>?>
  >
  getActivePreferences({
    required _i17.CuratedIngredientPreferenceListsRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActivePreferences, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<
                List<_i17.CuratedIngredientPreferenceListModel?>?
              >
            >.value(
              _FakeNetworkResponse_0<
                List<_i17.CuratedIngredientPreferenceListModel?>?
              >(
                this,
                Invocation.method(#getActivePreferences, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<
              List<_i17.CuratedIngredientPreferenceListModel?>?
            >
          >);

  @override
  _i4.Future<_i2.NetworkResponse<_i17.CuratedIngredientPreferenceListModel>?>
  saveIngredientPreferences({
    required _i17.SaveCuratedIngredientPreferencesRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveIngredientPreferences, [], {
              #request: request,
            }),
            returnValue:
                _i4.Future<
                  _i2.NetworkResponse<
                    _i17.CuratedIngredientPreferenceListModel
                  >?
                >.value(),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i17.CuratedIngredientPreferenceListModel>?
          >);

  @override
  _i4.Future<_i2.NetworkResponse<String>?> deleteIngredientPreferences({
    required int? userSelectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteIngredientPreferences, [], {
              #userSelectId: userSelectId,
            }),
            returnValue: _i4.Future<_i2.NetworkResponse<String>?>.value(),
          )
          as _i4.Future<_i2.NetworkResponse<String>?>);
}

/// A class which mocks [ProductDetailsAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductDetailsAnalytics extends _i1.Mock
    implements _i18.ProductDetailsAnalytics {
  MockProductDetailsAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> logProductDetailView({
    required _i19.ProductDetailBasicInformationModel? product,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logProductDetailView, [], {#product: product}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logSearchStart({required String? source}) =>
      (super.noSuchMethod(
            Invocation.method(#logSearchStart, [], {#source: source}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logScanStart({required String? source}) =>
      (super.noSuchMethod(
            Invocation.method(#logScanStart, [], {#source: source}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [IngredientPreferenceAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientPreferenceAnalytics extends _i1.Mock
    implements _i17.IngredientPreferenceAnalytics {
  MockIngredientPreferenceAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> logIngredientsPreferenceStart({required String? source}) =>
      (super.noSuchMethod(
            Invocation.method(#logIngredientsPreferenceStart, [], {
              #source: source,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logIngredientsPreferenceSet({
    required int? ingredientId,
    required bool? userSelected,
    required String? listType,
    required int? index,
    required String? action,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logIngredientsPreferenceSet, [], {
              #ingredientId: ingredientId,
              #userSelected: userSelected,
              #listType: listType,
              #index: index,
              #action: action,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logIngredientsPreferenceCuratedList({
    required _i17.CuratedIngredientPreferenceListModel? list,
    required int? index,
    required String? action,
    required String? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logIngredientsPreferenceCuratedList, [], {
              #list: list,
              #index: index,
              #action: action,
              #source: source,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logIngredientsPreferenceFilter({
    required String? filterName,
    required bool? enabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logIngredientsPreferenceFilter, [], {
              #filterName: filterName,
              #enabled: enabled,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
