arb-dir: lib/l10n
template-arb-file: app_en.arb

output-localization-file: healthy_living_scan_localizations.dart
output-class: HealthyLivingScanLocalizations

synthetic-package: false

untranslated-messages-file: lib/l10n/untranslated_messages.json