// Mocks generated by Mockito 5.4.6 from annotations
// in healthy_living_auth/test/repositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:healthy_living_auth/src/data/models/forgot_password_response_dto.dart'
    as _i10;
import 'package:healthy_living_auth/src/data/models/google_sign_in/google_sign_in_response_dto.dart'
    as _i2;
import 'package:healthy_living_auth/src/data/models/sign_in_response_dto.dart'
    as _i7;
import 'package:healthy_living_auth/src/data/models/sign_up_response_dto.dart'
    as _i13;
import 'package:healthy_living_auth/src/data/models/social_sign_in_request_model.dart'
    as _i9;
import 'package:healthy_living_auth/src/domain/data_source/auth_remote_data_source.dart'
    as _i4;
import 'package:healthy_living_auth/src/domain/models/change_password_request_model.dart'
    as _i17;
import 'package:healthy_living_auth/src/domain/models/edit_profile_request_model.dart'
    as _i16;
import 'package:healthy_living_auth/src/domain/models/forgot_password_request_model.dart'
    as _i11;
import 'package:healthy_living_auth/src/domain/models/reset_password_request_model.dart'
    as _i12;
import 'package:healthy_living_auth/src/domain/models/sign_in_request_model.dart'
    as _i8;
import 'package:healthy_living_auth/src/domain/models/sign_up_request_model.dart'
    as _i14;
import 'package:healthy_living_shared/healthy_living_shared.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/network.dart' as _i3;
import 'package:sign_in_with_apple/sign_in_with_apple.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGoogleSignInResponseDTO_0 extends _i1.SmartFake
    implements _i2.GoogleSignInResponseDTO {
  _FakeGoogleSignInResponseDTO_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNetworkResponse_1<T> extends _i1.SmartFake
    implements _i3.NetworkResponse<T> {
  _FakeNetworkResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i4.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.AuthorizationCredentialAppleID?> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue:
                _i5.Future<_i6.AuthorizationCredentialAppleID?>.value(),
          )
          as _i5.Future<_i6.AuthorizationCredentialAppleID?>);

  @override
  _i5.Future<_i2.GoogleSignInResponseDTO> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<_i2.GoogleSignInResponseDTO>.value(
              _FakeGoogleSignInResponseDTO_0(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i5.Future<_i2.GoogleSignInResponseDTO>);

  @override
  _i5.Future<_i3.NetworkResponse<_i7.SignInResponseDTO?>> signInWithEmail(
    _i8.SignInRequestModel? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [request]),
            returnValue:
                _i5.Future<_i3.NetworkResponse<_i7.SignInResponseDTO?>>.value(
                  _FakeNetworkResponse_1<_i7.SignInResponseDTO?>(
                    this,
                    Invocation.method(#signInWithEmail, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.NetworkResponse<_i7.SignInResponseDTO?>>);

  @override
  _i5.Future<_i3.NetworkResponse<_i7.SignInResponseDTO?>> socialSignIn({
    required _i9.SocialSignInRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#socialSignIn, [], {#request: request}),
            returnValue:
                _i5.Future<_i3.NetworkResponse<_i7.SignInResponseDTO?>>.value(
                  _FakeNetworkResponse_1<_i7.SignInResponseDTO?>(
                    this,
                    Invocation.method(#socialSignIn, [], {#request: request}),
                  ),
                ),
          )
          as _i5.Future<_i3.NetworkResponse<_i7.SignInResponseDTO?>>);

  @override
  _i5.Future<_i3.NetworkResponse<_i10.ForgotPasswordResponseDTO?>>
  requestResetPassword(_i11.ForgotPasswordRequestModel? request) =>
      (super.noSuchMethod(
            Invocation.method(#requestResetPassword, [request]),
            returnValue: _i5.Future<
              _i3.NetworkResponse<_i10.ForgotPasswordResponseDTO?>
            >.value(
              _FakeNetworkResponse_1<_i10.ForgotPasswordResponseDTO?>(
                this,
                Invocation.method(#requestResetPassword, [request]),
              ),
            ),
          )
          as _i5.Future<_i3.NetworkResponse<_i10.ForgotPasswordResponseDTO?>>);

  @override
  _i5.Future<_i3.NetworkResponse<_i7.SignInResponseDTO?>> resetPassword(
    _i12.ResetPasswordRequestModel? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue:
                _i5.Future<_i3.NetworkResponse<_i7.SignInResponseDTO?>>.value(
                  _FakeNetworkResponse_1<_i7.SignInResponseDTO?>(
                    this,
                    Invocation.method(#resetPassword, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.NetworkResponse<_i7.SignInResponseDTO?>>);

  @override
  _i5.Future<_i3.NetworkResponse<_i13.SignUpResponseDTO?>> signUpWithEmail(
    _i14.SignUpRequestModel? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [request]),
            returnValue:
                _i5.Future<_i3.NetworkResponse<_i13.SignUpResponseDTO?>>.value(
                  _FakeNetworkResponse_1<_i13.SignUpResponseDTO?>(
                    this,
                    Invocation.method(#signUpWithEmail, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.NetworkResponse<_i13.SignUpResponseDTO?>>);

  @override
  _i5.Future<_i3.NetworkResponse<_i15.UserDataDTO?>> saveProfile(
    _i16.EditProfileRequestModel? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveProfile, [request]),
            returnValue:
                _i5.Future<_i3.NetworkResponse<_i15.UserDataDTO?>>.value(
                  _FakeNetworkResponse_1<_i15.UserDataDTO?>(
                    this,
                    Invocation.method(#saveProfile, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.NetworkResponse<_i15.UserDataDTO?>>);

  @override
  _i5.Future<_i3.NetworkResponse<_i15.GeneralResponseDTO?>> changePassword(
    _i17.ChangePasswordRequestModel? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue:
                _i5.Future<_i3.NetworkResponse<_i15.GeneralResponseDTO?>>.value(
                  _FakeNetworkResponse_1<_i15.GeneralResponseDTO?>(
                    this,
                    Invocation.method(#changePassword, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.NetworkResponse<_i15.GeneralResponseDTO?>>);
}
