// Mocks generated by Mockito 5.4.6 from annotations
// in healthy_living_my_items/test/mock/mock_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:healthy_living_my_items/src/domain/respository/my_items_repository.dart'
    as _i3;
import 'package:healthy_living_shared/healthy_living_shared.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/network.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkResponse_0<T> extends _i1.SmartFake
    implements _i2.NetworkResponse<T> {
  _FakeNetworkResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MyItemsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyItemsRepository extends _i1.Mock implements _i3.MyItemsRepository {
  MockMyItemsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse<_i5.UserListModel?>> createMyItemList({
    required _i5.CreateListRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMyItemList, [], {#request: request}),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i5.UserListModel?>>.value(
                  _FakeNetworkResponse_0<_i5.UserListModel?>(
                    this,
                    Invocation.method(#createMyItemList, [], {
                      #request: request,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i5.UserListModel?>>);

  @override
  _i4.Future<_i2.NetworkResponse<List<_i5.UserListModel>?>> getUserList() =>
      (super.noSuchMethod(
            Invocation.method(#getUserList, []),
            returnValue:
                _i4.Future<_i2.NetworkResponse<List<_i5.UserListModel>?>>.value(
                  _FakeNetworkResponse_0<List<_i5.UserListModel>?>(
                    this,
                    Invocation.method(#getUserList, []),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<List<_i5.UserListModel>?>>);
}

/// A class which mocks [CreateListAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateListAnalytics extends _i1.Mock
    implements _i5.CreateListAnalytics {
  MockCreateListAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> logListCreated({
    required String? listId,
    required String? listName,
    int? itemCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logListCreated, [], {
              #listId: listId,
              #listName: listName,
              #itemCount: itemCount,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [HistoryProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryProductRepository extends _i1.Mock
    implements _i5.HistoryProductRepository {
  MockHistoryProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse<_i5.GeneralResponseModel?>>
  addRecentlyViewedProduct({
    required _i5.RecentlyViewedProductRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addRecentlyViewedProduct, [], {
              #request: request,
            }),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i5.GeneralResponseModel?>
            >.value(
              _FakeNetworkResponse_0<_i5.GeneralResponseModel?>(
                this,
                Invocation.method(#addRecentlyViewedProduct, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<_i5.GeneralResponseModel?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i5.GetHistoryResponseModel?>>
  getRecentlyViewed({required _i5.GetHistoryRequestModel? request}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyViewed, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i5.GetHistoryResponseModel?>
            >.value(
              _FakeNetworkResponse_0<_i5.GetHistoryResponseModel?>(
                this,
                Invocation.method(#getRecentlyViewed, [], {#request: request}),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<_i5.GetHistoryResponseModel?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i5.OcrProvisionalScoreResponseDTO?>>
  pollingOCRProvisionalScore({required String? jobId}) =>
      (super.noSuchMethod(
            Invocation.method(#pollingOCRProvisionalScore, [], {#jobId: jobId}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i5.OcrProvisionalScoreResponseDTO?>
            >.value(
              _FakeNetworkResponse_0<_i5.OcrProvisionalScoreResponseDTO?>(
                this,
                Invocation.method(#pollingOCRProvisionalScore, [], {
                  #jobId: jobId,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i5.OcrProvisionalScoreResponseDTO?>
          >);
}
