// Mocks generated by Mockito 5.4.6 from annotations
// in healthy_living_account/test/mock/mock_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:healthy_living_shared/healthy_living_shared.dart' as _i3;
import 'package:healthy_living_shared/src/domain/models/entitlements/entitlements_verify_response_model.dart'
    as _i5;
import 'package:healthy_living_shared/src/domain/models/user_token_data_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/network.dart' as _i2;
import 'package:storage/src/key_value_storage/key_value_storage.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkResponse_0<T> extends _i1.SmartFake
    implements _i2.NetworkResponse<T> {
  _FakeNetworkResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserDataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataRepository extends _i1.Mock
    implements _i3.UserDataRepository {
  MockUserDataRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveUserData(String? userDataModel) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [userDataModel]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.NetworkResponse<_i3.GeneralResponseDTO>> logoutUser() =>
      (super.noSuchMethod(
            Invocation.method(#logoutUser, []),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i3.GeneralResponseDTO>>.value(
                  _FakeNetworkResponse_0<_i3.GeneralResponseDTO>(
                    this,
                    Invocation.method(#logoutUser, []),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i3.GeneralResponseDTO>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i3.GeneralResponseDTO>> deleteUser() =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, []),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i3.GeneralResponseDTO>>.value(
                  _FakeNetworkResponse_0<_i3.GeneralResponseDTO>(
                    this,
                    Invocation.method(#deleteUser, []),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i3.GeneralResponseDTO>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i5.EntitlementsVerifyResponseModel>>
  verifyEntitlements() =>
      (super.noSuchMethod(
            Invocation.method(#verifyEntitlements, []),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i5.EntitlementsVerifyResponseModel>
            >.value(
              _FakeNetworkResponse_0<_i5.EntitlementsVerifyResponseModel>(
                this,
                Invocation.method(#verifyEntitlements, []),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i5.EntitlementsVerifyResponseModel>
          >);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i3.SessionRepository {
  MockSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> removeAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeAccessToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeRefreshToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeUserTokens() =>
      (super.noSuchMethod(
            Invocation.method(#removeUserTokens, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveIsAuthenticated(bool? isAuthenticated) =>
      (super.noSuchMethod(
            Invocation.method(#saveIsAuthenticated, [isAuthenticated]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> getIsAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#getIsAuthenticated, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<void> removeIsAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#removeIsAuthenticated, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.UserTokenDataModel?> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i4.Future<_i6.UserTokenDataModel?>.value(),
          )
          as _i4.Future<_i6.UserTokenDataModel?>);

  @override
  _i4.Future<void> saveIsPremiumUser(bool? isPremiumUser) =>
      (super.noSuchMethod(
            Invocation.method(#saveIsPremiumUser, [isPremiumUser]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> getIsPremiumUser() =>
      (super.noSuchMethod(
            Invocation.method(#getIsPremiumUser, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<void> removeIsPremiumUser() =>
      (super.noSuchMethod(
            Invocation.method(#removeIsPremiumUser, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> saveLogs({
    required String? message,
    bool? saveToFile = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveLogs, [], {
              #message: message,
              #saveToFile: saveToFile,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [KeyValueStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyValueStorage extends _i1.Mock implements _i7.KeyValueStorage {
  MockKeyValueStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int?> getInt(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getInt, [key]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<double?> getDouble(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key]),
            returnValue: _i4.Future<double?>.value(),
          )
          as _i4.Future<double?>);

  @override
  _i4.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool?> getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<String>?> getStringList(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getStringList, [key]),
            returnValue: _i4.Future<List<String>?>.value(),
          )
          as _i4.Future<List<String>?>);

  @override
  _i4.Future<bool> containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Set<String>> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: _i4.Future<Set<String>>.value(<String>{}),
          )
          as _i4.Future<Set<String>>);

  @override
  _i4.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [IngredientPreferenceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientPreferenceRepository extends _i1.Mock
    implements _i3.IngredientPreferenceRepository {
  MockIngredientPreferenceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
    _i2.NetworkResponse<_i3.CuratedIngredientPreferenceListsResponseModel?>
  >
  getCuratedIngredientPreferenceLists({
    required _i3.CuratedIngredientPreferenceListsRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCuratedIngredientPreferenceLists, [], {
              #request: request,
            }),
            returnValue: _i4.Future<
              _i2.NetworkResponse<
                _i3.CuratedIngredientPreferenceListsResponseModel?
              >
            >.value(
              _FakeNetworkResponse_0<
                _i3.CuratedIngredientPreferenceListsResponseModel?
              >(
                this,
                Invocation.method(#getCuratedIngredientPreferenceLists, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<
              _i3.CuratedIngredientPreferenceListsResponseModel?
            >
          >);

  @override
  _i4.Future<
    _i2.NetworkResponse<List<_i3.CuratedIngredientPreferenceListModel?>?>
  >
  getCuratedIngredientPreferences({
    required _i3.CuratedIngredientPreferenceListsRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCuratedIngredientPreferences, [], {
              #request: request,
            }),
            returnValue: _i4.Future<
              _i2.NetworkResponse<
                List<_i3.CuratedIngredientPreferenceListModel?>?
              >
            >.value(
              _FakeNetworkResponse_0<
                List<_i3.CuratedIngredientPreferenceListModel?>?
              >(
                this,
                Invocation.method(#getCuratedIngredientPreferences, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<
              List<_i3.CuratedIngredientPreferenceListModel?>?
            >
          >);

  @override
  _i4.Future<
    _i2.NetworkResponse<List<_i3.CuratedIngredientPreferenceListModel?>?>
  >
  getActivePreferences({
    required _i3.CuratedIngredientPreferenceListsRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActivePreferences, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<
                List<_i3.CuratedIngredientPreferenceListModel?>?
              >
            >.value(
              _FakeNetworkResponse_0<
                List<_i3.CuratedIngredientPreferenceListModel?>?
              >(
                this,
                Invocation.method(#getActivePreferences, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<
              List<_i3.CuratedIngredientPreferenceListModel?>?
            >
          >);

  @override
  _i4.Future<_i2.NetworkResponse<_i3.CuratedIngredientPreferenceListModel>?>
  saveIngredientPreferences({
    required _i3.SaveCuratedIngredientPreferencesRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveIngredientPreferences, [], {
              #request: request,
            }),
            returnValue:
                _i4.Future<
                  _i2.NetworkResponse<_i3.CuratedIngredientPreferenceListModel>?
                >.value(),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i3.CuratedIngredientPreferenceListModel>?
          >);

  @override
  _i4.Future<_i2.NetworkResponse<String>?> deleteIngredientPreferences({
    required int? userSelectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteIngredientPreferences, [], {
              #userSelectId: userSelectId,
            }),
            returnValue: _i4.Future<_i2.NetworkResponse<String>?>.value(),
          )
          as _i4.Future<_i2.NetworkResponse<String>?>);
}

/// A class which mocks [IngredientPreferenceAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientPreferenceAnalytics extends _i1.Mock
    implements _i3.IngredientPreferenceAnalytics {
  MockIngredientPreferenceAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> logIngredientsPreferenceStart({required String? source}) =>
      (super.noSuchMethod(
            Invocation.method(#logIngredientsPreferenceStart, [], {
              #source: source,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logIngredientsPreferenceSet({
    required int? ingredientId,
    required bool? userSelected,
    required String? listType,
    required int? index,
    required String? action,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logIngredientsPreferenceSet, [], {
              #ingredientId: ingredientId,
              #userSelected: userSelected,
              #listType: listType,
              #index: index,
              #action: action,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logIngredientsPreferenceCuratedList({
    required _i3.CuratedIngredientPreferenceListModel? list,
    required int? index,
    required String? action,
    required String? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logIngredientsPreferenceCuratedList, [], {
              #list: list,
              #index: index,
              #action: action,
              #source: source,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logIngredientsPreferenceFilter({
    required String? filterName,
    required bool? enabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logIngredientsPreferenceFilter, [], {
              #filterName: filterName,
              #enabled: enabled,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
