arb-dir: lib/l10n
template-arb-file: app_en.arb

output-localization-file: healthy_living_account_localizations.dart
output-class: HealthyLivingAccountLocalizations

synthetic-package: false

untranslated-messages-file: lib/l10n/untranslated_messages.json