// Mocks generated by Mockito 5.4.6 from annotations
// in healthy_living_shared/test/repositories/history_product_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:healthy_living_shared/healthy_living_shared.dart' as _i5;
import 'package:healthy_living_shared/src/domain/data_source/history_product_remote_data_source.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/network.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkResponse_0<T> extends _i1.SmartFake
    implements _i2.NetworkResponse<T> {
  _FakeNetworkResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HistoryProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryProductRemoteDataSource extends _i1.Mock
    implements _i3.HistoryProductRemoteDataSource {
  MockHistoryProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse<_i5.GeneralResponseDTO?>>
  addRecentlyViewedProduct(_i5.RecentlyViewedProductRequestDTO? request) =>
      (super.noSuchMethod(
            Invocation.method(#addRecentlyViewedProduct, [request]),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i5.GeneralResponseDTO?>>.value(
                  _FakeNetworkResponse_0<_i5.GeneralResponseDTO?>(
                    this,
                    Invocation.method(#addRecentlyViewedProduct, [request]),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i5.GeneralResponseDTO?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i5.GetHistoryResponseDTO?>>
  getRecentlyViewed({required _i5.GetHistoryRequestDTO? request}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyViewed, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i5.GetHistoryResponseDTO?>
            >.value(
              _FakeNetworkResponse_0<_i5.GetHistoryResponseDTO?>(
                this,
                Invocation.method(#getRecentlyViewed, [], {#request: request}),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<_i5.GetHistoryResponseDTO?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i5.OcrProvisionalScoreResponseDTO?>>
  pollingOCRProvisionalScore({required String? jobId}) =>
      (super.noSuchMethod(
            Invocation.method(#pollingOCRProvisionalScore, [], {#jobId: jobId}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i5.OcrProvisionalScoreResponseDTO?>
            >.value(
              _FakeNetworkResponse_0<_i5.OcrProvisionalScoreResponseDTO?>(
                this,
                Invocation.method(#pollingOCRProvisionalScore, [], {
                  #jobId: jobId,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i5.OcrProvisionalScoreResponseDTO?>
          >);
}
