// Mocks generated by Mockito 5.4.6 from annotations
// in healthy_living_shared/test/repositories/ingredient_preference_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:healthy_living_shared/healthy_living_shared.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/network.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkResponse_0<T> extends _i1.SmartFake
    implements _i2.NetworkResponse<T> {
  _FakeNetworkResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IngredientPreferenceRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientPreferenceRemoteDataSource extends _i1.Mock
    implements _i3.IngredientPreferenceRemoteDataSource {
  MockIngredientPreferenceRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
    _i2.NetworkResponse<_i3.CuratedIngredientPreferenceListsResponseDto?>
  >
  getCuratedIngredientPreferenceLists({
    required _i3.CuratedIngredientPreferenceListsRequestDto? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCuratedIngredientPreferenceLists, [], {
              #request: request,
            }),
            returnValue: _i4.Future<
              _i2.NetworkResponse<
                _i3.CuratedIngredientPreferenceListsResponseDto?
              >
            >.value(
              _FakeNetworkResponse_0<
                _i3.CuratedIngredientPreferenceListsResponseDto?
              >(
                this,
                Invocation.method(#getCuratedIngredientPreferenceLists, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<
              _i3.CuratedIngredientPreferenceListsResponseDto?
            >
          >);

  @override
  _i4.Future<
    _i2.NetworkResponse<_i3.CuratedIngredientPreferenceListsResponseDto?>
  >
  getCuratedIngredientPreferences({
    required _i3.CuratedIngredientPreferenceListsRequestDto? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCuratedIngredientPreferences, [], {
              #request: request,
            }),
            returnValue: _i4.Future<
              _i2.NetworkResponse<
                _i3.CuratedIngredientPreferenceListsResponseDto?
              >
            >.value(
              _FakeNetworkResponse_0<
                _i3.CuratedIngredientPreferenceListsResponseDto?
              >(
                this,
                Invocation.method(#getCuratedIngredientPreferences, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<
              _i3.CuratedIngredientPreferenceListsResponseDto?
            >
          >);

  @override
  _i4.Future<
    _i2.NetworkResponse<_i3.CuratedIngredientPreferenceListsResponseDto?>
  >
  getActivePreferences({
    required _i3.CuratedIngredientPreferenceListsRequestDto? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActivePreferences, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<
                _i3.CuratedIngredientPreferenceListsResponseDto?
              >
            >.value(
              _FakeNetworkResponse_0<
                _i3.CuratedIngredientPreferenceListsResponseDto?
              >(
                this,
                Invocation.method(#getActivePreferences, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<
              _i3.CuratedIngredientPreferenceListsResponseDto?
            >
          >);

  @override
  _i4.Future<_i2.NetworkResponse<_i3.CuratedIngredientPreferenceListDto?>?>
  saveIngredientPreferences({
    required _i3.SaveCuratedIngredientPreferencesRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveIngredientPreferences, [], {
              #request: request,
            }),
            returnValue:
                _i4.Future<
                  _i2.NetworkResponse<_i3.CuratedIngredientPreferenceListDto?>?
                >.value(),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i3.CuratedIngredientPreferenceListDto?>?
          >);

  @override
  _i4.Future<_i2.NetworkResponse<String?>?> deleteIngredientPreferences({
    required int? userSelectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteIngredientPreferences, [], {
              #userSelectId: userSelectId,
            }),
            returnValue: _i4.Future<_i2.NetworkResponse<String?>?>.value(),
          )
          as _i4.Future<_i2.NetworkResponse<String?>?>);
}
