// Mocks generated by Mockito 5.4.6 from annotations
// in healthy_living_shared/test/repositories/my_list_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:healthy_living_shared/healthy_living_shared.dart' as _i5;
import 'package:healthy_living_shared/src/domain/data_source/my_list_remote_data_source.dart'
    as _i3;
import 'package:healthy_living_shared/src/domain/models/user_list/add_to_list_request_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/network.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkResponse_0<T> extends _i1.SmartFake
    implements _i2.NetworkResponse<T> {
  _FakeNetworkResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MyListRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyListRemoteDataSource extends _i1.Mock
    implements _i3.MyListRemoteDataSource {
  MockMyListRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse<List<_i5.UserListDTO?>?>> getUsersLists() =>
      (super.noSuchMethod(
            Invocation.method(#getUsersLists, []),
            returnValue:
                _i4.Future<_i2.NetworkResponse<List<_i5.UserListDTO?>?>>.value(
                  _FakeNetworkResponse_0<List<_i5.UserListDTO?>?>(
                    this,
                    Invocation.method(#getUsersLists, []),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<List<_i5.UserListDTO?>?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i5.UserListDTO?>> addProductToList({
    required _i6.AddToListRequestModel? addToListRequestModel,
    required String? listId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addProductToList, [], {
              #addToListRequestModel: addToListRequestModel,
              #listId: listId,
            }),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i5.UserListDTO?>>.value(
                  _FakeNetworkResponse_0<_i5.UserListDTO?>(
                    this,
                    Invocation.method(#addProductToList, [], {
                      #addToListRequestModel: addToListRequestModel,
                      #listId: listId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i5.UserListDTO?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i5.UserListDetailDTO?>> createMyItemList({
    required _i5.CreateListRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMyItemList, [], {#request: request}),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i5.UserListDetailDTO?>>.value(
                  _FakeNetworkResponse_0<_i5.UserListDetailDTO?>(
                    this,
                    Invocation.method(#createMyItemList, [], {
                      #request: request,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i5.UserListDetailDTO?>>);
}
