// Mocks generated by Mockito 5.4.6 from annotations
// in healthy_living_shared/test/repositories/newsletter_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:healthy_living_shared/src/data/models/newsletter_subscription_response_dto.dart'
    as _i5;
import 'package:healthy_living_shared/src/domain/data_source/newsletter_remote_data_source.dart'
    as _i3;
import 'package:healthy_living_shared/src/domain/models/newsletter/newsletter_subscription_request_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/network.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkResponse_0<T> extends _i1.SmartFake
    implements _i2.NetworkResponse<T> {
  _FakeNetworkResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NewsletterRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsletterRemoteDataSource extends _i1.Mock
    implements _i3.NewsletterRemoteDataSource {
  MockNewsletterRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse<_i5.NewsletterSubscriptionResponseDTO?>>
  subscribeToNewsletter(_i6.NewsletterSubscriptionRequestModel? request) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToNewsletter, [request]),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i5.NewsletterSubscriptionResponseDTO?>
            >.value(
              _FakeNetworkResponse_0<_i5.NewsletterSubscriptionResponseDTO?>(
                this,
                Invocation.method(#subscribeToNewsletter, [request]),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i5.NewsletterSubscriptionResponseDTO?>
          >);
}
