// Mocks generated by Mockito 5.4.6 from annotations
// in healthy_living_shared/test/repositories/user_data_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:healthy_living_shared/src/data/models/entitlements/entitlements_verify_response_dto.dart'
    as _i7;
import 'package:healthy_living_shared/src/data/models/general_response_dto.dart'
    as _i6;
import 'package:healthy_living_shared/src/domain/data_source/user_data_local_data_source.dart'
    as _i3;
import 'package:healthy_living_shared/src/domain/data_source/user_data_remote_data_source.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/network.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkResponse_0<T> extends _i1.SmartFake
    implements _i2.NetworkResponse<T> {
  _FakeNetworkResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserDataLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataLocalDataSource extends _i1.Mock
    implements _i3.UserDataLocalDataSource {
  MockUserDataLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveUserData(String? userDataModel) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [userDataModel]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [UserDataRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataRemoteDataSource extends _i1.Mock
    implements _i5.UserDataRemoteDataSource {
  MockUserDataRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse<_i6.GeneralResponseDTO>> logoutUser() =>
      (super.noSuchMethod(
            Invocation.method(#logoutUser, []),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i6.GeneralResponseDTO>>.value(
                  _FakeNetworkResponse_0<_i6.GeneralResponseDTO>(
                    this,
                    Invocation.method(#logoutUser, []),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i6.GeneralResponseDTO>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i6.GeneralResponseDTO>> deleteUser() =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, []),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i6.GeneralResponseDTO>>.value(
                  _FakeNetworkResponse_0<_i6.GeneralResponseDTO>(
                    this,
                    Invocation.method(#deleteUser, []),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i6.GeneralResponseDTO>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i7.EntitlementsVerifyResponseDto?>>
  verifyEntitlements() =>
      (super.noSuchMethod(
            Invocation.method(#verifyEntitlements, []),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i7.EntitlementsVerifyResponseDto?>
            >.value(
              _FakeNetworkResponse_0<_i7.EntitlementsVerifyResponseDto?>(
                this,
                Invocation.method(#verifyEntitlements, []),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i7.EntitlementsVerifyResponseDto?>
          >);
}
