// Mocks generated by Mockito 5.4.6 from annotations
// in healthy_living_find/test/mock/mock_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:healthy_living_find/src/analytics/browse_analytics.dart' as _i9;
import 'package:healthy_living_find/src/analytics/search_analytics.dart' as _i7;
import 'package:healthy_living_find/src/domain/models/search_product_model.dart'
    as _i8;
import 'package:healthy_living_find/src/domain/models/search_request_model.dart'
    as _i6;
import 'package:healthy_living_find/src/domain/models/search_response_model.dart'
    as _i5;
import 'package:healthy_living_find/src/domain/repository/universal_search_repository.dart'
    as _i3;
import 'package:healthy_living_shared/healthy_living_shared.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/network.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkResponse_0<T> extends _i1.SmartFake
    implements _i2.NetworkResponse<T> {
  _FakeNetworkResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UniversalSearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUniversalSearchRepository extends _i1.Mock
    implements _i3.UniversalSearchRepository {
  MockUniversalSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse<_i5.SearchResponseModel?>> universalSearch({
    required _i6.SearchRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#universalSearch, [], {#request: request}),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i5.SearchResponseModel?>>.value(
                  _FakeNetworkResponse_0<_i5.SearchResponseModel?>(
                    this,
                    Invocation.method(#universalSearch, [], {
                      #request: request,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i5.SearchResponseModel?>>);
}

/// A class which mocks [SearchAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchAnalytics extends _i1.Mock implements _i7.SearchAnalytics {
  MockSearchAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> logSearchStart({required String? source}) =>
      (super.noSuchMethod(
            Invocation.method(#logSearchStart, [], {#source: source}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logSearch({
    required String? searchTerm,
    required String? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSearch, [], {
              #searchTerm: searchTerm,
              #source: source,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logViewSearchResults({
    required String? searchTerm,
    required int? resultCount,
    required String? source,
    List<_i8.SearchProductModel>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewSearchResults, [], {
              #searchTerm: searchTerm,
              #resultCount: resultCount,
              #source: source,
              #items: items,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logSearchResultClick({
    required _i8.SearchProductModel? product,
    required int? position,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSearchResultClick, [], {
              #product: product,
              #position: position,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logScanStart({required String? source}) =>
      (super.noSuchMethod(
            Invocation.method(#logScanStart, [], {#source: source}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [BrowseAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockBrowseAnalytics extends _i1.Mock implements _i9.BrowseAnalytics {
  MockBrowseAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> logBrowseProductType({
    required String? productType,
    required List<_i10.BrowseMainCategoryModel>? categories,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logBrowseProductType, [], {
              #productType: productType,
              #categories: categories,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logBrowseCategoryGroup({
    required String? productType,
    required String? categoryGroupId,
    required List<_i8.SearchProductModel>? items,
    bool? isEWGVerified,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logBrowseCategoryGroup, [], {
              #productType: productType,
              #categoryGroupId: categoryGroupId,
              #items: items,
              #isEWGVerified: isEWGVerified,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logBrowseCategory({
    required String? productType,
    required String? categoryId,
    required List<_i8.SearchProductModel>? items,
    bool? isEWGVerified,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logBrowseCategory, [], {
              #productType: productType,
              #categoryId: categoryId,
              #items: items,
              #isEWGVerified: isEWGVerified,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logBrowseSubCategory({
    required String? productType,
    required String? subCategoryId,
    required List<_i8.SearchProductModel>? items,
    bool? isEWGVerified,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logBrowseSubCategory, [], {
              #productType: productType,
              #subCategoryId: subCategoryId,
              #items: items,
              #isEWGVerified: isEWGVerified,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logBrowseVerified({
    required List<_i8.SearchProductModel>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logBrowseVerified, [], {#items: items}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
