// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stage.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwPz93ypNbQpZI76mnyz9ddpZg_qGrXtM',
    appId: '1:1037709831582:android:026df4e8950f1d85b9fa8f',
    messagingSenderId: '1037709831582',
    projectId: 'ewg-healthyliving-staging',
    storageBucket: 'ewg-healthyliving-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjNXnc6VPfnR4OTKfbLUo9ciB7xBAgyQg',
    appId: '1:1037709831582:ios:7de2799becb7d6cbb9fa8f',
    messagingSenderId: '1037709831582',
    projectId: 'ewg-healthyliving-staging',
    storageBucket: 'ewg-healthyliving-staging.firebasestorage.app',
    androidClientId: '1037709831582-6vd64via6ukp6vc41hf1pc88daco8brl.apps.googleusercontent.com',
    iosBundleId: 'com.healthyliving.mobile.stage',
  );

}