// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2e-hc11M88B1czmcuqy6J4xKe7xti_Vg',
    appId: '1:654386197077:android:513a75e85697455a9a5adc',
    messagingSenderId: '654386197077',
    projectId: 'ewg-healthyliving',
    databaseURL: 'https://ewg-healthyliving.firebaseio.com',
    storageBucket: 'ewg-healthyliving.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3LPxJC3cdqs3EfzFzxnim8rb4zLnVj9I',
    appId: '1:654386197077:ios:7c0053c02483012d9a5adc',
    messagingSenderId: '654386197077',
    projectId: 'ewg-healthyliving',
    databaseURL: 'https://ewg-healthyliving.firebaseio.com',
    storageBucket: 'ewg-healthyliving.firebasestorage.app',
    androidClientId: '654386197077-5m80286mn31ihi3ja537341l2hmbfv66.apps.googleusercontent.com',
    iosClientId: '654386197077-q07scaq41i4pb052fee423f7tkduelpj.apps.googleusercontent.com',
    iosBundleId: 'skindeepR',
  );
}
