// Mocks generated by Mockito 5.4.6 from annotations
// in healthy_living_product_detail/test/repositories/product_detail_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:healthy_living_product_detail/src/data/models/cleaner_detail_response_dto.dart'
    as _i7;
import 'package:healthy_living_product_detail/src/data/models/cosmetic_detail_response_dto.dart'
    as _i5;
import 'package:healthy_living_product_detail/src/data/models/food_detail_response_dto.dart'
    as _i9;
import 'package:healthy_living_product_detail/src/data/models/ingredient_details/ingredient_info_response_dto.dart'
    as _i11;
import 'package:healthy_living_product_detail/src/data/models/product_compare_cleaners_response_dto.dart'
    as _i15;
import 'package:healthy_living_product_detail/src/data/models/product_compare_cosmetic_response_dto.dart'
    as _i13;
import 'package:healthy_living_product_detail/src/data/models/product_compare_food_response_dto.dart'
    as _i16;
import 'package:healthy_living_product_detail/src/domain/data_source/product_detail_remote_data_source.dart'
    as _i3;
import 'package:healthy_living_product_detail/src/domain/models/cleaner_detail_request_model.dart'
    as _i8;
import 'package:healthy_living_product_detail/src/domain/models/cosmetic_detail_request_model.dart'
    as _i6;
import 'package:healthy_living_product_detail/src/domain/models/food_detail_request_model.dart'
    as _i10;
import 'package:healthy_living_product_detail/src/domain/models/ingredient_details/ingredient_info_request_model.dart'
    as _i12;
import 'package:healthy_living_product_detail/src/domain/models/product_compare_request_model.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/network.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkResponse_0<T> extends _i1.SmartFake
    implements _i2.NetworkResponse<T> {
  _FakeNetworkResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductDetailRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductDetailRemoteDataSource extends _i1.Mock
    implements _i3.ProductDetailRemoteDataSource {
  MockProductDetailRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse<_i5.CosmeticDetailResponseDTO?>>
  getCosmeticDetails({required _i6.CosmeticDetailRequestModel? request}) =>
      (super.noSuchMethod(
            Invocation.method(#getCosmeticDetails, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i5.CosmeticDetailResponseDTO?>
            >.value(
              _FakeNetworkResponse_0<_i5.CosmeticDetailResponseDTO?>(
                this,
                Invocation.method(#getCosmeticDetails, [], {#request: request}),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<_i5.CosmeticDetailResponseDTO?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i7.CleanerDetailResponseDTO?>>
  getCleanerDetails({required _i8.CleanerDetailRequestModel? request}) =>
      (super.noSuchMethod(
            Invocation.method(#getCleanerDetails, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i7.CleanerDetailResponseDTO?>
            >.value(
              _FakeNetworkResponse_0<_i7.CleanerDetailResponseDTO?>(
                this,
                Invocation.method(#getCleanerDetails, [], {#request: request}),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<_i7.CleanerDetailResponseDTO?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i9.FoodDetailResponseDTO?>> getFoodDetails({
    required _i10.FoodDetailRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodDetails, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i9.FoodDetailResponseDTO?>
            >.value(
              _FakeNetworkResponse_0<_i9.FoodDetailResponseDTO?>(
                this,
                Invocation.method(#getFoodDetails, [], {#request: request}),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<_i9.FoodDetailResponseDTO?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i11.IngredientInfoResponseDTO?>>
  getIngredientInfo({required _i12.IngredientInfoRequestModel? request}) =>
      (super.noSuchMethod(
            Invocation.method(#getIngredientInfo, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i11.IngredientInfoResponseDTO?>
            >.value(
              _FakeNetworkResponse_0<_i11.IngredientInfoResponseDTO?>(
                this,
                Invocation.method(#getIngredientInfo, [], {#request: request}),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<_i11.IngredientInfoResponseDTO?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i13.ProductCompareCosmeticResponseDTO?>>
  getProductComparisonCosmeticDetails({
    required _i14.ProductCompareRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductComparisonCosmeticDetails, [], {
              #request: request,
            }),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i13.ProductCompareCosmeticResponseDTO?>
            >.value(
              _FakeNetworkResponse_0<_i13.ProductCompareCosmeticResponseDTO?>(
                this,
                Invocation.method(#getProductComparisonCosmeticDetails, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i13.ProductCompareCosmeticResponseDTO?>
          >);

  @override
  _i4.Future<_i2.NetworkResponse<_i15.ProductCompareCleanersResponseDTO?>>
  getProductComparisonCleanersDetails({
    required _i14.ProductCompareRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductComparisonCleanersDetails, [], {
              #request: request,
            }),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i15.ProductCompareCleanersResponseDTO?>
            >.value(
              _FakeNetworkResponse_0<_i15.ProductCompareCleanersResponseDTO?>(
                this,
                Invocation.method(#getProductComparisonCleanersDetails, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i15.ProductCompareCleanersResponseDTO?>
          >);

  @override
  _i4.Future<_i2.NetworkResponse<_i16.ProductCompareFoodResponseDTO?>>
  getProductComparisonFoodDetails({
    required _i14.ProductCompareRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductComparisonFoodDetails, [], {
              #request: request,
            }),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i16.ProductCompareFoodResponseDTO?>
            >.value(
              _FakeNetworkResponse_0<_i16.ProductCompareFoodResponseDTO?>(
                this,
                Invocation.method(#getProductComparisonFoodDetails, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i16.ProductCompareFoodResponseDTO?>
          >);
}
