// Mocks generated by Mockito 5.4.6 from annotations
// in healthy_living_auth/test/mock/mock_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:firebase_analytics/firebase_analytics.dart' as _i20;
import 'package:healthy_living_auth/src/analytics/auth_analytics.dart' as _i21;
import 'package:healthy_living_auth/src/core/purchase_user_service.dart'
    as _i22;
import 'package:healthy_living_auth/src/data/models/sign_in_social_result.dart'
    as _i2;
import 'package:healthy_living_auth/src/data/models/social_sign_in_request_model.dart'
    as _i9;
import 'package:healthy_living_auth/src/domain/models/change_password_request_model.dart'
    as _i17;
import 'package:healthy_living_auth/src/domain/models/edit_profile_request_model.dart'
    as _i16;
import 'package:healthy_living_auth/src/domain/models/forgot_password_request_model.dart'
    as _i11;
import 'package:healthy_living_auth/src/domain/models/forgot_password_response_model.dart'
    as _i10;
import 'package:healthy_living_auth/src/domain/models/google_sign_in/google_sign_in_response_model.dart'
    as _i3;
import 'package:healthy_living_auth/src/domain/models/reset_password_request_model.dart'
    as _i13;
import 'package:healthy_living_auth/src/domain/models/sign_in_request_model.dart'
    as _i8;
import 'package:healthy_living_auth/src/domain/models/sign_in_response_model.dart'
    as _i7;
import 'package:healthy_living_auth/src/domain/models/sign_up_request_model.dart'
    as _i15;
import 'package:healthy_living_auth/src/domain/models/sign_up_response_model.dart'
    as _i14;
import 'package:healthy_living_auth/src/domain/repository/auth_repository.dart'
    as _i5;
import 'package:healthy_living_shared/healthy_living_shared.dart' as _i12;
import 'package:healthy_living_shared/src/domain/models/user_token_data_model.dart'
    as _i18;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/network.dart' as _i4;
import 'package:storage/src/key_value_storage/key_value_storage.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignInSocialResult_0 extends _i1.SmartFake
    implements _i2.SignInSocialResult {
  _FakeSignInSocialResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleSignInResponseModel_1 extends _i1.SmartFake
    implements _i3.GoogleSignInResponseModel {
  _FakeGoogleSignInResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNetworkResponse_2<T> extends _i1.SmartFake
    implements _i4.NetworkResponse<T> {
  _FakeNetworkResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.SignInSocialResult> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i6.Future<_i2.SignInSocialResult>.value(
              _FakeSignInSocialResult_0(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
          )
          as _i6.Future<_i2.SignInSocialResult>);

  @override
  _i6.Future<_i3.GoogleSignInResponseModel> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i6.Future<_i3.GoogleSignInResponseModel>.value(
              _FakeGoogleSignInResponseModel_1(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i6.Future<_i3.GoogleSignInResponseModel>);

  @override
  _i6.Future<_i4.NetworkResponse<_i7.SignInResponseModel?>> signInWithEmail({
    required _i8.SignInRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [], {#request: request}),
            returnValue:
                _i6.Future<_i4.NetworkResponse<_i7.SignInResponseModel?>>.value(
                  _FakeNetworkResponse_2<_i7.SignInResponseModel?>(
                    this,
                    Invocation.method(#signInWithEmail, [], {
                      #request: request,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.NetworkResponse<_i7.SignInResponseModel?>>);

  @override
  _i6.Future<_i4.NetworkResponse<_i7.SignInResponseModel?>> socialSignIn({
    required _i9.SocialSignInRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#socialSignIn, [], {#request: request}),
            returnValue:
                _i6.Future<_i4.NetworkResponse<_i7.SignInResponseModel?>>.value(
                  _FakeNetworkResponse_2<_i7.SignInResponseModel?>(
                    this,
                    Invocation.method(#socialSignIn, [], {#request: request}),
                  ),
                ),
          )
          as _i6.Future<_i4.NetworkResponse<_i7.SignInResponseModel?>>);

  @override
  _i6.Future<_i4.NetworkResponse<_i10.ForgotPasswordResponseModel?>>
  requestResetPassword({required _i11.ForgotPasswordRequestModel? request}) =>
      (super.noSuchMethod(
            Invocation.method(#requestResetPassword, [], {#request: request}),
            returnValue: _i6.Future<
              _i4.NetworkResponse<_i10.ForgotPasswordResponseModel?>
            >.value(
              _FakeNetworkResponse_2<_i10.ForgotPasswordResponseModel?>(
                this,
                Invocation.method(#requestResetPassword, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i6.Future<
            _i4.NetworkResponse<_i10.ForgotPasswordResponseModel?>
          >);

  @override
  _i6.Future<_i4.NetworkResponse<_i12.UserDataModel?>> resetPassword({
    required _i13.ResetPasswordRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#request: request}),
            returnValue:
                _i6.Future<_i4.NetworkResponse<_i12.UserDataModel?>>.value(
                  _FakeNetworkResponse_2<_i12.UserDataModel?>(
                    this,
                    Invocation.method(#resetPassword, [], {#request: request}),
                  ),
                ),
          )
          as _i6.Future<_i4.NetworkResponse<_i12.UserDataModel?>>);

  @override
  _i6.Future<_i4.NetworkResponse<_i14.SignUpResponseModel?>> signUpWithEmail({
    required _i15.SignUpRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [], {#request: request}),
            returnValue: _i6.Future<
              _i4.NetworkResponse<_i14.SignUpResponseModel?>
            >.value(
              _FakeNetworkResponse_2<_i14.SignUpResponseModel?>(
                this,
                Invocation.method(#signUpWithEmail, [], {#request: request}),
              ),
            ),
          )
          as _i6.Future<_i4.NetworkResponse<_i14.SignUpResponseModel?>>);

  @override
  _i6.Future<_i4.NetworkResponse<_i12.UserDataModel?>> saveProfile({
    required _i16.EditProfileRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveProfile, [], {#request: request}),
            returnValue:
                _i6.Future<_i4.NetworkResponse<_i12.UserDataModel?>>.value(
                  _FakeNetworkResponse_2<_i12.UserDataModel?>(
                    this,
                    Invocation.method(#saveProfile, [], {#request: request}),
                  ),
                ),
          )
          as _i6.Future<_i4.NetworkResponse<_i12.UserDataModel?>>);

  @override
  _i6.Future<_i4.NetworkResponse<_i12.GeneralResponseModel?>> changePassword({
    required _i17.ChangePasswordRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {#request: request}),
            returnValue: _i6.Future<
              _i4.NetworkResponse<_i12.GeneralResponseModel?>
            >.value(
              _FakeNetworkResponse_2<_i12.GeneralResponseModel?>(
                this,
                Invocation.method(#changePassword, [], {#request: request}),
              ),
            ),
          )
          as _i6.Future<_i4.NetworkResponse<_i12.GeneralResponseModel?>>);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i12.SessionRepository {
  MockSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> removeAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeAccessToken, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeRefreshToken, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeUserTokens() =>
      (super.noSuchMethod(
            Invocation.method(#removeUserTokens, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveIsAuthenticated(bool? isAuthenticated) =>
      (super.noSuchMethod(
            Invocation.method(#saveIsAuthenticated, [isAuthenticated]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool?> getIsAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#getIsAuthenticated, []),
            returnValue: _i6.Future<bool?>.value(),
          )
          as _i6.Future<bool?>);

  @override
  _i6.Future<void> removeIsAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#removeIsAuthenticated, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i18.UserTokenDataModel?> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i6.Future<_i18.UserTokenDataModel?>.value(),
          )
          as _i6.Future<_i18.UserTokenDataModel?>);

  @override
  _i6.Future<void> saveIsPremiumUser(bool? isPremiumUser) =>
      (super.noSuchMethod(
            Invocation.method(#saveIsPremiumUser, [isPremiumUser]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool?> getIsPremiumUser() =>
      (super.noSuchMethod(
            Invocation.method(#getIsPremiumUser, []),
            returnValue: _i6.Future<bool?>.value(),
          )
          as _i6.Future<bool?>);

  @override
  _i6.Future<void> removeIsPremiumUser() =>
      (super.noSuchMethod(
            Invocation.method(#removeIsPremiumUser, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> saveLogs({
    required String? message,
    bool? saveToFile = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveLogs, [], {
              #message: message,
              #saveToFile: saveToFile,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [KeyValueStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyValueStorage extends _i1.Mock implements _i19.KeyValueStorage {
  MockKeyValueStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String?> getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<int?> getInt(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getInt, [key]),
            returnValue: _i6.Future<int?>.value(),
          )
          as _i6.Future<int?>);

  @override
  _i6.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<double?> getDouble(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key]),
            returnValue: _i6.Future<double?>.value(),
          )
          as _i6.Future<double?>);

  @override
  _i6.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool?> getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValue: _i6.Future<bool?>.value(),
          )
          as _i6.Future<bool?>);

  @override
  _i6.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<String>?> getStringList(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getStringList, [key]),
            returnValue: _i6.Future<List<String>?>.value(),
          )
          as _i6.Future<List<String>?>);

  @override
  _i6.Future<bool> containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<Set<String>> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: _i6.Future<Set<String>>.value(<String>{}),
          )
          as _i6.Future<Set<String>>);

  @override
  _i6.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i12.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> logEvent({
    required String? name,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [], {
              #name: name,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logScreenView({
    required String? screenName,
    String? screenClass,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logScreenView, [], {
              #screenName: screenName,
              #screenClass: screenClass,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logViewItem({
    required String? itemId,
    required String? itemName,
    required String? productType,
    String? brandName,
    String? categoryGroup,
    String? category,
    String? subCategory,
    String? otherCategory,
    bool? isEwgVerified,
    String? score,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewItem, [], {
              #itemId: itemId,
              #itemName: itemName,
              #productType: productType,
              #brandName: brandName,
              #categoryGroup: categoryGroup,
              #category: category,
              #subCategory: subCategory,
              #otherCategory: otherCategory,
              #isEwgVerified: isEwgVerified,
              #score: score,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logViewItemList({
    required String? itemListId,
    required String? itemListName,
    required List<_i20.AnalyticsEventItem>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewItemList, [], {
              #itemListId: itemListId,
              #itemListName: itemListName,
              #items: items,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logSearch({
    required String? searchTerm,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSearch, [], {
              #searchTerm: searchTerm,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logViewSearchResults({
    required String? searchTerm,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewSearchResults, [], {
              #searchTerm: searchTerm,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logSelectItem({
    required String? itemListName,
    required List<_i20.AnalyticsEventItem>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSelectItem, [], {
              #itemListName: itemListName,
              #items: items,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setUserProperty({
    required String? name,
    required String? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [], {
              #name: name,
              #value: value,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearUser, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AuthAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthAnalytics extends _i1.Mock implements _i21.AuthAnalytics {
  MockAuthAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> logLogin({required String? method}) =>
      (super.noSuchMethod(
            Invocation.method(#logLogin, [], {#method: method}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logSignUp({required String? method}) =>
      (super.noSuchMethod(
            Invocation.method(#logSignUp, [], {#method: method}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logLoginSkip({required String? source}) =>
      (super.noSuchMethod(
            Invocation.method(#logLoginSkip, [], {#source: source}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [PurchaseUserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPurchaseUserService extends _i1.Mock
    implements _i22.PurchaseUserService {
  MockPurchaseUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> syncUserDetails(_i12.UserDataModel? userData) =>
      (super.noSuchMethod(
            Invocation.method(#syncUserDetails, [userData]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
