// Mocks generated by Mockito 5.4.6 from annotations
// in healthy_living_home/test/repositories/home_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:healthy_living_home/src/data/models/recent_activity/recent_activity_response_dto.dart'
    as _i7;
import 'package:healthy_living_home/src/domain/data_source/home_remote_data_source.dart'
    as _i3;
import 'package:healthy_living_home/src/domain/models/home_your_list_request.dart'
    as _i6;
import 'package:healthy_living_home/src/domain/models/just_verified_request_model.dart'
    as _i8;
import 'package:healthy_living_shared/healthy_living_shared.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/network.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkResponse_0<T> extends _i1.SmartFake
    implements _i2.NetworkResponse<T> {
  _FakeNetworkResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i3.HomeRemoteDataSource {
  MockHomeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse<List<_i5.UserListDTO>?>> getYourLists({
    required _i6.HomeYourListRequest? homeYourListRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getYourLists, [], {
              #homeYourListRequest: homeYourListRequest,
            }),
            returnValue:
                _i4.Future<_i2.NetworkResponse<List<_i5.UserListDTO>?>>.value(
                  _FakeNetworkResponse_0<List<_i5.UserListDTO>?>(
                    this,
                    Invocation.method(#getYourLists, [], {
                      #homeYourListRequest: homeYourListRequest,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<List<_i5.UserListDTO>?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i7.RecentActivityResponseDTO?>>
  getRecentViewList() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentViewList, []),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i7.RecentActivityResponseDTO?>
            >.value(
              _FakeNetworkResponse_0<_i7.RecentActivityResponseDTO?>(
                this,
                Invocation.method(#getRecentViewList, []),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<_i7.RecentActivityResponseDTO?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i5.SearchResponseDTO?>> getJustVerified({
    required _i8.JustVerifiedRequestModel? justVerifiedRequestModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getJustVerified, [], {
              #justVerifiedRequestModel: justVerifiedRequestModel,
            }),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i5.SearchResponseDTO?>>.value(
                  _FakeNetworkResponse_0<_i5.SearchResponseDTO?>(
                    this,
                    Invocation.method(#getJustVerified, [], {
                      #justVerifiedRequestModel: justVerifiedRequestModel,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i5.SearchResponseDTO?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i5.UserListDetailDTO?>> createYourList({
    required _i5.CreateListRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createYourList, [], {#request: request}),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i5.UserListDetailDTO?>>.value(
                  _FakeNetworkResponse_0<_i5.UserListDetailDTO?>(
                    this,
                    Invocation.method(#createYourList, [], {#request: request}),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i5.UserListDetailDTO?>>);
}
