// Mocks generated by Mockito 5.4.6 from annotations
// in healthy_living_shared/test/mock/mock_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_analytics/firebase_analytics.dart' as _i12;
import 'package:healthy_living_shared/healthy_living_shared.dart' as _i3;
import 'package:healthy_living_shared/src/domain/models/entitlements/entitlements_verify_response_model.dart'
    as _i6;
import 'package:healthy_living_shared/src/domain/models/newsletter/newsletter_subscription_response_model.dart'
    as _i7;
import 'package:healthy_living_shared/src/domain/models/user_list/add_to_list_request_model.dart'
    as _i10;
import 'package:healthy_living_shared/src/domain/models/user_token_data_model.dart'
    as _i5;
import 'package:healthy_living_shared/src/domain/repository/my_list_detail_repository.dart'
    as _i11;
import 'package:healthy_living_shared/src/domain/repository/my_list_repository.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/network.dart' as _i2;
import 'package:storage/src/key_value_storage/key_value_storage.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkResponse_0<T> extends _i1.SmartFake
    implements _i2.NetworkResponse<T> {
  _FakeNetworkResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i3.SessionRepository {
  MockSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> removeAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeAccessToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeRefreshToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeUserTokens() =>
      (super.noSuchMethod(
            Invocation.method(#removeUserTokens, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveIsAuthenticated(bool? isAuthenticated) =>
      (super.noSuchMethod(
            Invocation.method(#saveIsAuthenticated, [isAuthenticated]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> getIsAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#getIsAuthenticated, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<void> removeIsAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#removeIsAuthenticated, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.UserTokenDataModel?> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i4.Future<_i5.UserTokenDataModel?>.value(),
          )
          as _i4.Future<_i5.UserTokenDataModel?>);

  @override
  _i4.Future<void> saveIsPremiumUser(bool? isPremiumUser) =>
      (super.noSuchMethod(
            Invocation.method(#saveIsPremiumUser, [isPremiumUser]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> getIsPremiumUser() =>
      (super.noSuchMethod(
            Invocation.method(#getIsPremiumUser, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<void> removeIsPremiumUser() =>
      (super.noSuchMethod(
            Invocation.method(#removeIsPremiumUser, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> saveLogs({
    required String? message,
    bool? saveToFile = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveLogs, [], {
              #message: message,
              #saveToFile: saveToFile,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [UserDataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataRepository extends _i1.Mock
    implements _i3.UserDataRepository {
  MockUserDataRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveUserData(String? userDataModel) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [userDataModel]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.NetworkResponse<_i3.GeneralResponseDTO>> logoutUser() =>
      (super.noSuchMethod(
            Invocation.method(#logoutUser, []),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i3.GeneralResponseDTO>>.value(
                  _FakeNetworkResponse_0<_i3.GeneralResponseDTO>(
                    this,
                    Invocation.method(#logoutUser, []),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i3.GeneralResponseDTO>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i3.GeneralResponseDTO>> deleteUser() =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, []),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i3.GeneralResponseDTO>>.value(
                  _FakeNetworkResponse_0<_i3.GeneralResponseDTO>(
                    this,
                    Invocation.method(#deleteUser, []),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i3.GeneralResponseDTO>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i6.EntitlementsVerifyResponseModel>>
  verifyEntitlements() =>
      (super.noSuchMethod(
            Invocation.method(#verifyEntitlements, []),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i6.EntitlementsVerifyResponseModel>
            >.value(
              _FakeNetworkResponse_0<_i6.EntitlementsVerifyResponseModel>(
                this,
                Invocation.method(#verifyEntitlements, []),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i6.EntitlementsVerifyResponseModel>
          >);
}

/// A class which mocks [NewsletterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsletterRepository extends _i1.Mock
    implements _i3.NewsletterRepository {
  MockNewsletterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse<_i7.NewsletterSubscriptionResponseModel?>>
  subscribeToNewsletter({
    required _i3.NewsletterSubscriptionRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToNewsletter, [], {#request: request}),
            returnValue: _i4.Future<
              _i2.NetworkResponse<_i7.NewsletterSubscriptionResponseModel?>
            >.value(
              _FakeNetworkResponse_0<_i7.NewsletterSubscriptionResponseModel?>(
                this,
                Invocation.method(#subscribeToNewsletter, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<
            _i2.NetworkResponse<_i7.NewsletterSubscriptionResponseModel?>
          >);
}

/// A class which mocks [SessionLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionLocalDataSource extends _i1.Mock
    implements _i3.SessionLocalDataSource {
  MockSessionLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeAccessToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeRefreshToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> saveIsAuthenticated(bool? isAuthenticated) =>
      (super.noSuchMethod(
            Invocation.method(#saveIsAuthenticated, [isAuthenticated]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> getIsAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#getIsAuthenticated, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<void> removeIsAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#removeIsAuthenticated, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setIsPremiumUser(bool? isPremiumUser) =>
      (super.noSuchMethod(
            Invocation.method(#setIsPremiumUser, [isPremiumUser]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> getIsPremiumUser() =>
      (super.noSuchMethod(
            Invocation.method(#getIsPremiumUser, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<void> removeIsPremiumUser() =>
      (super.noSuchMethod(
            Invocation.method(#removeIsPremiumUser, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> saveLogs(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#saveLogs, [message]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> getLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getLogs, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}

/// A class which mocks [SessionRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRemoteDataSource extends _i1.Mock
    implements _i3.SessionRemoteDataSource {
  MockSessionRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.UserTokenDataModel?> refreshToken({
    required String? refreshToken,
    required String? accessToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [], {
              #refreshToken: refreshToken,
              #accessToken: accessToken,
            }),
            returnValue: _i4.Future<_i5.UserTokenDataModel?>.value(),
          )
          as _i4.Future<_i5.UserTokenDataModel?>);
}

/// A class which mocks [KeyValueStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyValueStorage extends _i1.Mock implements _i8.KeyValueStorage {
  MockKeyValueStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int?> getInt(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getInt, [key]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<double?> getDouble(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key]),
            returnValue: _i4.Future<double?>.value(),
          )
          as _i4.Future<double?>);

  @override
  _i4.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool?> getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<String>?> getStringList(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getStringList, [key]),
            returnValue: _i4.Future<List<String>?>.value(),
          )
          as _i4.Future<List<String>?>);

  @override
  _i4.Future<bool> containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Set<String>> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: _i4.Future<Set<String>>.value(<String>{}),
          )
          as _i4.Future<Set<String>>);

  @override
  _i4.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [MyListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyListRepository extends _i1.Mock implements _i9.MyListRepository {
  MockMyListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse<List<_i3.UserListModel>?>> getUsersLists() =>
      (super.noSuchMethod(
            Invocation.method(#getUsersLists, []),
            returnValue:
                _i4.Future<_i2.NetworkResponse<List<_i3.UserListModel>?>>.value(
                  _FakeNetworkResponse_0<List<_i3.UserListModel>?>(
                    this,
                    Invocation.method(#getUsersLists, []),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<List<_i3.UserListModel>?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>> addProductToList({
    required _i10.AddToListRequestModel? addToListRequestModel,
    required String? listId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addProductToList, [], {
              #addToListRequestModel: addToListRequestModel,
              #listId: listId,
            }),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>>.value(
                  _FakeNetworkResponse_0<_i3.UserListModel?>(
                    this,
                    Invocation.method(#addProductToList, [], {
                      #addToListRequestModel: addToListRequestModel,
                      #listId: listId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>> createMyItemList({
    required _i3.CreateListRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMyItemList, [], {#request: request}),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>>.value(
                  _FakeNetworkResponse_0<_i3.UserListModel?>(
                    this,
                    Invocation.method(#createMyItemList, [], {
                      #request: request,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>>);
}

/// A class which mocks [MyListDetailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyListDetailRepository extends _i1.Mock
    implements _i11.MyListDetailRepository {
  MockMyListDetailRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>> productListFromListId({
    required String? listId,
    required int? page,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#productListFromListId, [], {
              #listId: listId,
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>>.value(
                  _FakeNetworkResponse_0<_i3.UserListModel?>(
                    this,
                    Invocation.method(#productListFromListId, [], {
                      #listId: listId,
                      #page: page,
                      #pageSize: pageSize,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>> userListFromListId({
    required String? listId,
    required int? page,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#userListFromListId, [], {
              #listId: listId,
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>>.value(
                  _FakeNetworkResponse_0<_i3.UserListModel?>(
                    this,
                    Invocation.method(#userListFromListId, [], {
                      #listId: listId,
                      #page: page,
                      #pageSize: pageSize,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>>);

  @override
  _i4.Future<_i2.NetworkResponse<dynamic>> deleteList({
    required String? listId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteList, [], {#listId: listId}),
            returnValue: _i4.Future<_i2.NetworkResponse<dynamic>>.value(
              _FakeNetworkResponse_0<dynamic>(
                this,
                Invocation.method(#deleteList, [], {#listId: listId}),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<dynamic>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i3.UserListModel>> deleteProductsList({
    required String? listId,
    required _i10.AddToListRequestModel? addToListRequestModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductsList, [], {
              #listId: listId,
              #addToListRequestModel: addToListRequestModel,
            }),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i3.UserListModel>>.value(
                  _FakeNetworkResponse_0<_i3.UserListModel>(
                    this,
                    Invocation.method(#deleteProductsList, [], {
                      #listId: listId,
                      #addToListRequestModel: addToListRequestModel,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i3.UserListModel>>);

  @override
  _i4.Future<_i2.NetworkResponse<dynamic>> renameList({
    required String? listId,
    required _i3.CreateListRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renameList, [], {
              #listId: listId,
              #request: request,
            }),
            returnValue: _i4.Future<_i2.NetworkResponse<dynamic>>.value(
              _FakeNetworkResponse_0<dynamic>(
                this,
                Invocation.method(#renameList, [], {
                  #listId: listId,
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.NetworkResponse<dynamic>>);

  @override
  _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>> addProductToList({
    required _i10.AddToListRequestModel? addToListRequestModel,
    required String? listId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addProductToList, [], {
              #addToListRequestModel: addToListRequestModel,
              #listId: listId,
            }),
            returnValue:
                _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>>.value(
                  _FakeNetworkResponse_0<_i3.UserListModel?>(
                    this,
                    Invocation.method(#addProductToList, [], {
                      #addToListRequestModel: addToListRequestModel,
                      #listId: listId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.NetworkResponse<_i3.UserListModel?>>);
}

/// A class which mocks [PaywallAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaywallAnalytics extends _i1.Mock implements _i3.PaywallAnalytics {
  MockPaywallAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> logPaywallView({required String? source}) =>
      (super.noSuchMethod(
            Invocation.method(#logPaywallView, [], {#source: source}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logPaywallClose({required String? source}) =>
      (super.noSuchMethod(
            Invocation.method(#logPaywallClose, [], {#source: source}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logPaywallSubmit({
    required String? subscriptionId,
    required String? entitlementId,
    required bool? active,
    required String? environment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logPaywallSubmit, [], {
              #subscriptionId: subscriptionId,
              #entitlementId: entitlementId,
              #active: active,
              #environment: environment,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [CreateListAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateListAnalytics extends _i1.Mock
    implements _i3.CreateListAnalytics {
  MockCreateListAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> logListCreated({
    required String? listId,
    required String? listName,
    int? itemCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logListCreated, [], {
              #listId: listId,
              #listName: listName,
              #itemCount: itemCount,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i3.AnalyticsService {
  @override
  _i4.Future<void> logEvent({
    required String? name,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [], {
              #name: name,
              #parameters: parameters,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logScreenView({
    required String? screenName,
    String? screenClass,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logScreenView, [], {
              #screenName: screenName,
              #screenClass: screenClass,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logViewItem({
    required String? itemId,
    required String? itemName,
    required String? productType,
    String? brandName,
    String? categoryGroup,
    String? category,
    String? subCategory,
    String? otherCategory,
    bool? isEwgVerified,
    String? score,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewItem, [], {
              #itemId: itemId,
              #itemName: itemName,
              #productType: productType,
              #brandName: brandName,
              #categoryGroup: categoryGroup,
              #category: category,
              #subCategory: subCategory,
              #otherCategory: otherCategory,
              #isEwgVerified: isEwgVerified,
              #score: score,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logViewItemList({
    required String? itemListId,
    required String? itemListName,
    required List<_i12.AnalyticsEventItem>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewItemList, [], {
              #itemListId: itemListId,
              #itemListName: itemListName,
              #items: items,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logSearch({
    required String? searchTerm,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSearch, [], {
              #searchTerm: searchTerm,
              #parameters: parameters,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logViewSearchResults({
    required String? searchTerm,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewSearchResults, [], {
              #searchTerm: searchTerm,
              #parameters: parameters,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logSelectItem({
    required String? itemListName,
    required List<_i12.AnalyticsEventItem>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSelectItem, [], {
              #itemListName: itemListName,
              #items: items,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserProperty({
    required String? name,
    required String? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [], {
              #name: name,
              #value: value,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearUser, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
